### ISSUE TITLE
Adaptation feedback

### ISSUE THREAD

**Issue by fansanqiu** [dive2Pro/roam-native-dark#2]
I like this extension very much; it can provide me with a more comfortable writing environment and follow the system setting. That's very useful.

But I got a problem here.

When I use the Daily Notes Popup feature of the Workbench extension, the color looks so strange.

<img width="842" alt="Screenshot 2023-01-05 at 21 40 22" src="https://user-images.githubusercontent.com/58503364/210795026-6bf6a31a-a4d6-420b-a302-2c1ff0b4520c.png">

**Comment by dive2Pro** [comment]
Hey, you can add this css snippet to your graph
```css
.bp3-dark .bg-white {
   background: var(--dark-bg);
}

```

**Comment by fansanqiu** [comment]
It works! Thanks.
